import 'package:predict_ipl/team/TeamClass.dart';

const Teams = [
  Team(name: 'CSK', imageAddress: 'images/csk.png', players: [
    'MS Dhoni',
    'Suresh Raina',
    'Shane Watson',
    'Dwayne Bravo',
    'Faf du Plesis',
    'Imhran Tahir',
    'Ravindra Jadeja',
    'Lungi Ngidi',
    'Ambati Rayudu',
    'Sam Curran',
    'Josh Hazlewood',
    'Shradul Thakur',
    'Murali Vijay',
    'Kedar Jadav',
    'Deppak Chahar',
    'Piyush Chawla',
    'Mitchell Santner',
    'Karn Sharma',
    'Ruturaj Gaikwad',
    'Narayan Jagadeesan',
    'Sai Kishore',
    'Monu Kumar',
  ]),
  Team(name: 'MI', imageAddress: 'images/mi.png', players: [
    'Rohit Sharma',
    'Kieron Pollard',
    'de Kock',
    'Aditya Tare',
    'Hardik Pandya',
    'Ishan Kishan',
    'Jasprit Bumrah',
    'Krunal Pandya',
    'M McClenaghan',
    'Trent Boult',
    'Chris Lynn',
    'Coulter-Nile',
    'Sowrabh Tiwary',
    'James Pattinson',
    'Suryakumar Yadav',
    'Deshmkuh',
    'Jayant Yadav',
    'Rahul Chahar',
    'Dhawal Kulkarni',
    'Shrefane Rutherford',
    'Anmolpreet Singh',
    'Mohsin Khan',
    'Ankul Roy',
    'Balwant Singh',
  ]),
  Team(name: 'RCB', imageAddress: 'images/rcb.png', players: [
    'Virat Kohli',
    'AB de Villiers',
    'Aaron Finch',
    'Dale Steyn',
    'Yuzvendra Chahal',
    'Chris Morris',
    'Moeen Ali',
    'Mohammed Siraj',
    'Navdeep Saini',
    'Parthiv Patel',
    'Pawan Negi',
    'Shivam Dube',
    'Umesh Yadav',
    'Washington Sundar',
    'Isuru Udana',
    'Adam Zampa',
    'Josh Philippe',
    'Pavan Deshpande',
    'Shahbaz Ahamad',
    'Devdutt Padikkal',
    'Gurkeerat Singh',
  ]),
  Team(name: 'SRH', imageAddress: 'images/srh.png', players: [
    'David Warner',
    'Bhuvneshwar Kumar',
    'Rashid Khan',
    'Johny Bairstow',
    'Kane Williamson',
    'Manish Pandey',
    'Mohammad Nabi',
    'Vijay Shankar',
    'Sandeep Sharma',
    'Mitchell Marsh',
    'Wriddhiman Saha',
    'Abhishek Sharma',
    'Basil Thampi',
    'Billy Stanlake',
    'Shahbaz Nadeem',
    'Shreevats Goswami',
    'Siddarth Kaul',
    'Khaleel Ahmed',
    'T Natarajan',
    'Virat Singh',
    'Priyag Garg',
    'Sandeeep Bavanaka',
    'Fabian Allen',
    'Abdul Samad',
    'Sanjay Yadav',
  ]),
  Team(name: 'RR', imageAddress: 'images/rr.png', players: [
    'Steve Smith',
    'Ben Stokes',
    'Sanju Samson',
    'Andrew Tye',
    'Jaydev Unadkat',
    'Jofra Archer',
    'David Miller',
    'Jos Buttler',
    'Robin Uthappa',
    'Vraun Aaron',
    'Mayank Markande',
    'Shreyas Gopal',
    'Rahul Tewatia',
    'Manan Vohra',
    'Karthik Tyagi',
    'Shahshank Singh',
    'Ankit Rajpoot',
    'Mahipal Lomror',
    'Oshane Thomas',
    'Riyan Parag',
    'Yashasvi Jaiswal',
    'Anuj Rawat',
    'Akash Singh',
    'Tom Curran',
    'Anirudha Joshi',
  ]),
  Team(name: 'KXIP', imageAddress: 'images/kxip.png', players: [
    'KL Rahul',
    'Chris Gayle',
    'Glenn Maxwell',
    'Mohammad Shami',
    'Mayank Agarwal',
    'Sheldon Cottrell',
    'Karun Nair',
    'Mandeep Singh',
    'Nicholas Pooran',
    'Sarfaraz Khan',
    'Murugan Ashwin',
    'Ur Rahman',
    'Deepak Hooda',
    'Ishan Porel',
    'Ravi Bishnoi',
    'Jimmy Neesham',
    'Arshdeep Singh',
    'Darshan Nalkande',
    'K Gowtham',
    'Hardus Viljoen',
    'Harpreet Brar',
    'J Suchith',
    'Chris Jordan',
    'Tajinder Singh',
    'Simran Singh',
  ]),
  Team(name: 'KKR', imageAddress: 'images/kkr.png', players: [
    'Dinesh Karthik',
    'Sunil Narine',
    'Andre Russell',
    'Eoin Morgan',
    'Pat Cummins',
    'Kuldeep Yadav',
    'Lockie Ferguson',
    'Rahul Tripathi',
    'Shubam Gill',
    'Nitish Rana',
    'Prasidh Krishna',
    'Rinku Singh',
    'Sandeep Warrier',
    'Harry Gurney',
    'Kamlesh Nagarkoti',
    'Shivam Mavi',
    'Siddhesh Lad',
    'V Chakravarthy',
    'M Siddharth',
    'Chris Green',
    'Tom Banton',
    'Nikhil Naik',
  ]),
  Team(name: 'DC', imageAddress: 'images/dc.png', players: [
    'R Ashwin',
    'Shikar Dhawan',
    'Shreyas Iyer',
    'Ajinkya Rahane',
    'Marcus Stoinis',
    'Rishab Pant',
    'Marcus Stoinis',
    'Shimron Hetmyer',
    'Mohit Sharma',
    'Lalith Yadav',
    'Amit Mishra',
    'Axar Patel',
    'Ishant Sharma',
    'Prithvi Shaw',
    'Kagiso Rabada',
    'Harshal Patel',
    'Sandeep L',
    'Avesh Khan',
    'Alex Carey',
    'T Deshpande',
    'Anirch Nortje',
    'Daniel Sams',
  ]),
  Team(name: 'BLANK', imageAddress: 'images/blank.jpg', players: [
    'Select a player',
  ]),
];
